spring:
  application:
    name: spring-boot-base-backend-single
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.190.86.22:10086/exam_manage
    username: HeTong
    password: zl08250901@YL
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    context-path: /
  port: 8080
logging:
  level:
    root: INFO
  file:
    name: logs/base-admin.log
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true
    banner: false

uploadPath: H:/Intelligent_Teaching_Assistant_Resource/

deepseek:
  api-key: sk-44552729da4f4c429c04d2514da409c7
  api-url: https://api.deepseek.com/v1/chat/completions

